version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "uni-prop-dev-contracts"
s3_prefix = "uni-prop-dev-contracts"
s3_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-79mz06fv3jcb"
region = "ap-southeast-2"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"

# ############################################## #

[2]
[2.global]
[2.global.parameters]
stack_name = "uni-prop-prod-contracts"
s3_prefix = "uni-prop-prod-contracts"
s3_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-16e3ioqv3jp51"
region = "ap-southeast-2"

[2.deploy]
[2.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "uni-prop-contracts-pipeline"
s3_prefix = "uni-prop-contracts-pipeline"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
